mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.main, name='main'),
    path('quest/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('account/login', views.BBLoginView.as_view(), name='login'),
    path('account/profile/', views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    image = models.ImageField(upload_to="uploads/", null=True, blank=False)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_message = models.BooleanField(default=True, verbose_name='Оповещать при новых комментариях?')


class Meta(AbstractUser.Meta):
    pass

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def main(request):
    return render(request, 'polls/main.html')


class BBLoginView(LoginView):
    template_name = 'polls/login.html'


@login_required
def profile(request):
    return render(request, 'polls/profile.html')

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a> </li>
    {% endfor %}
</ul>
    {% else %}
     <p>
         Нет вопросов!
     </p>

{% endif %}

mysite/polls/templates/polls/login.html
{% extends "polls/main.html" %}
{% load bootstrap4 %}
{% block title %} Вход {% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

mysite/polls/templates/polls/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysite/polls/templates/polls/main.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devicewidth, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">-->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %} -
        Опрос </title>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="mr-md-auto p-2">опрос</h5>
        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#"
               data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">Профиль</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'polls:profile' %}">Мои
                    объявления</a>
                <a class="dropdown-item" href="#">Изменить
                    личные данные</a>
                <a class="dropdown-item" href="#">Изменить
                    пароль</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Выйти</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                   href="#">Удалить</a>
            </div>
        </div>
        {% else %}
        <a class="p-2 text-dark" href="#">Регистрация</a>
        <a class="p-2 text-dark" href="{% url 'polls:login' %}">Вход</a>
        {% endif %}
    </div>
    <div>
        <a class="nav-link root" href="quest/">Пройти опрос</a>
    </div>
    <footer class="mt-3 border-top">
        <small class="p-2"> &copy; Знакомство с
            фреймворком
            Django. 2018-2019
        </small>
    </footer>
</div>
</body>
</html>

mysite/polls/templates/polls/profile.html
{% extends "polls/main.html" %}
{% load bootstrap4 %}
{% block title %} Профиль пользователя {% endblock %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{
    user.last_name }} </p>
{% else %}
<p>Здравствуйте! </p>
{% endif %}
<h3>Ваши объявления</h3>
{% endblock %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail'  question.id %}">выбрать еще раз? </a>